"""
    sms-client

    API for sms-send functions  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import com.nvt.celman
from com.nvt.celman.model.sms_send_response import SmsSendResponse


class TestSmsSendResponse(unittest.TestCase):
    """SmsSendResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSmsSendResponse(self):
        """Test SmsSendResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SmsSendResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
