"""
    sms-client

    API for sms-send functions  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import com.nvt.celman
from com.nvt.celman.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sms_send(self):
        """Test case for sms_send

        Send a text message request.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
