"""
    sms-client

    API for sms-send functions  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import com.nvt.celman
from com.nvt.celman.model.sms_send_request import SmsSendRequest


class TestSmsSendRequest(unittest.TestCase):
    """SmsSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSmsSendRequest(self):
        """Test SmsSendRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SmsSendRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
